FROM node:12.18.1-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY ./src ./src

RUN npm install -g migrate
CMD cd src && \

# You actually do want to run migrate each time to get new collections added
#    migrate down && \
 ##   migrate up && \
 ##   node bin/import-data.js && \ 
    mirate up && \
    npm start 